### PR TITLE
* Added Radiobutton support

### PR DESCRIPTION
**Pull request by seryal**
* Added Radiobutton support

### CODE REVIEW

**Comment by seryal** [comment]
You mean icons like a Radiobutton :)
image

**Comment by pascaldragon** [comment]
Thank you, but it seems that there is something wrong with the size calculation, cause at least in Firefox it results in wrapping:
wcl-radiobutton
Even if the text is too long it should never wrap.

**Comment by seryal** [comment]
> Thank you, but it seems that there is something wrong with the size calculation, cause at least in Firefox it results in wrapping:
> wcl-radiobutton
> Even if the text is too long it should never wrap.

Ok.
I use Chrome. But I will check this on other brothsers. Thanks.

**Comment by pascaldragon** [comment]
You should also add `TWRadioButton` to the list of components of the `RegisterComponentRequirements` call in `pas2js_ide_descriptor.Register`

**Comment by seryal** [comment]
Fixed.

**Comment by pascaldragon** [comment]
Looks better, though there is still a sizing issue. But I've noticed that with other components es well, so we'll probably have to find a more general solution here. 🤔

wcl-radiobutton-2

**Comment by seryal** [comment]
My knowledge of HTML coding is not that strong and i often find it difficult to align elements 😃

**Comment by pascaldragon** [comment]
> My knowledge of HTML coding is not that strong and i often find it difficult to align elements 😃

You and me both... 😅

**Comment by pascaldragon** [comment]
Thank you very much!

**Pull request merged**
