### PR TITLE
Fixed project template.

### PR DESCRIPTION
**Pull request by seryal**
Now the application can be created from the menu Project - New Project - Web GUI Application.

### CODE REVIEW

**Comment by pascaldragon** [comment]
Please keep the compatibility at the level of Pas2JS 2.0.0 for now. One could argue that Lazarus 2.1 would be better instead of 2.0.12, but at least the compiler version should be a fixed one now (though I'm aware that there might be code already that expects functionality from pas2js 2.1 like the recent StrToTimeDef fix showed).

**Comment by seryal** [comment]
When i try use Lazarus 2.0.12 with Pas2JS 2.0.
I get an error in the browser "_Caught unknown exception type : Cannot read property 'InheritsFrom' of null_".
But if the form is empty, then there is no error. After drop TWpanel to Form from WCL tab, this error appears. 

Lazarus 2.0.12 with Pas2Js 2.0 - **Error**
Lazarus 2.0.12 with Pas2Js 2.1.1 (trunk) - **Error**
Lazarus 2.1 (trunk) with Pas2Js 2.0 - **Error**
Lazarus 2.1 (trunk) with Pas2Js 2.1.1 (trunk) - **Work**

Why this error occurs, I have not studied deeply.

I would like to know, you have the same results?

**Comment by seryal** [comment]
Wrong statement
> Lazarus 2.1 (trunk) with Pas2Js 2.0 - Error

Right statement
Lazarus 2.1 (trunk) with Pas2Js 2.0 - **Work**

### Final report:

- Lazarus 2.0.12 with Pas2Js 2.0 - **Error**
- Lazarus 2.0.12 with Pas2Js 2.1.1 (trunk) - **Error**
- Lazarus 2.1 (trunk) with Pas2Js 2.0 - **Work**
- Lazarus 2.1 (trunk) with Pas2Js 2.1.1 (trunk) - **Work**

PS: pas2js i complie with Free Pascal Compiler version 3.3.1-r49211 [2021/04/17] for x86_64

**Comment by pascaldragon** [comment]
Thanks for testing. So if you adjust the Readme to recommend Pas2JS 2.0 again I'll merge this. 😊

**Comment by seryal** [comment]
I have corrected the description.

**Comment by pascaldragon** [comment]
Thank you!

**Pull request merged**
