### PR TITLE
* Changed icons for the palette

### PR DESCRIPTION
**Pull request by seryal**
I redraw all icons.
image
What do you think?

### CODE REVIEW

**Comment by pascaldragon** [comment]
Not bad, the W looks definitely nice.

However I'd simply reuse the LCL icons together with the W overlay to simplify things when new icons are needed.

**Comment by seryal** [comment]
I did so, but some elements are not in the standard palette :) as `TWFloatEdit`, `TWIntegerEdit`, `TWPagination`, `TWFileButton`.
And for `TWDataGrid `and `TWStringGrid` I have not come up with a normal visual difference

**Comment by pascaldragon** [comment]
But the icons of the LCL have blue “text” instead of red? The idea is that for those components that exist in both the LCL and the WCL one can simply use the LCL's icon and use some script involving e.g. ImageMagick to overlay the W and be done. No need to change the “text” color or anything.

Obviously for those components that don't exist in the LCL we need our own icons, but those can follow the same scheme: the base icon plus the W with the help of a script.

This way if we have a better idea for the overlay we can easily recreate the images without much hazzle. Or if the LCL uses a more fancy icon for something.

**Comment by seryal** [comment]
OK. No problem. I will redraw the icons from the standard palette. 👍

**Comment by pascaldragon** [comment]
Oh, and please no .pdn files. Best just add the final icons, the raw icons for components that the LCL does not contain as well as the W-overlay, all as PNG files.

**Comment by seryal** [comment]
Like this?
image

**Comment by pascaldragon** [comment]
Yes! 😍

**Comment by pascaldragon** [comment]
Would you maybe also copy the relevant entries of the `images/copyright.txt` from Lazarus into a `copyright.txt` of our own? (and maybe also add entries for those you did yourself?)

**Comment by seryal** [comment]
The images pack is as follows:

> LICENSE AND COPYRIGHT INFORMATION ABOUT IMAGES USED IN  Pas2JS_Widget
> ------------------------------------------------------------------
>
> The following original component palette icons were created by Roland Hahn (no restrictions). 
> Modified by the team Pas2JS_Widget
> 	twcombobox.png
> 	twlistbox.png
> 	twedit.png
> 	twmemo.png
> 	twbutton.png
> 	twcheckbox.png
> 	twradiobutton.png
> 	twlabel.png
> 	twimage.png
> 	twpanel.png
> 	twtimer.png
> 	twpagecontrol.png
> 	twdateedit.png
> 	twtimeedit.png
> 	twstringgrid.png
> 
> The following component palette icons were created by team Pas2JS_Widget
> 	twfloatedit.png
> 	twintegeredit.png
> 	twfilebutton.png
> 	twpagination.png
> 	twwebsocketclient.png
> 

But I am afraid that I will not be able to correctly compose copyright.txt. My knowledge of English is not very good. :(
I have to use a gogle translator from time to time :)

Could you create the file yourself? 😏

**Pull request closed without merging**
